### ISSUE TITLE
Content Suggestion: Do you have any plan to add tests?

### ISSUE THREAD

**Issue by DanKim0213** [mdn/todo-react#120]
Hi, I love this todo-react project and I've learned so much about React through this project. 

However, I feel starving to learn tests ever since testing is becoming one of the requirements to be hired. I think this project could be a good start for junior frontend developers to learn not only React but also testing :) 

Thus, I wonder if you have any plan to add tests with [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/). And, if so, can I pull requests?

**Comment by bsmth** [comment]
> Hi, I love this todo-react project and I've learned so much about React through this project.

Hi there 👋🏻 that's really great to hear.

> ... testing is becoming one of the requirements to be hired. I think this project could be a good start for junior frontend developers to learn not only React but also testing :)

I think that's a really good point. It might be nice to have something generic about functional testing, especially since Node.js has [a test runner since Node 20](https://nodejs.org/api/test.html).

Do you want to [add an issue here for a feature proposal](https://github.com/mdn/mdn/issues/new/choose) so we can figure out where it could live?

**Comment by DanKim0213** [comment]
> Do you want to [add an issue here for a feature proposal](https://github.com/mdn/mdn/issues/new/choose) so we can figure out where it could live?

Hi, thanks for your reply 👋

I added [this issue to MDN](https://github.com/mdn/mdn/issues/525) for a feature proposal as you said :)

**Comment by bsmth** [comment]
Super, thank you! Let's close this and track progress in your proposal - issues in this repo are moreso for reporting and tracking bugs in the code.
